my_blog/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

from article.views import article_list, page_not_found

urlpatterns = [
    path('', article_list, name='home'),
    # 启用media
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}, name='media'),

    path('admin/', admin.site.urls),
    # 文章
    path('article/', include('article.urls', namespace='article')),

    # 评论
    path('comment/', include('comment.urls', namespace='comment')),

    # 用户
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),

    # 引用轮子
    # 密码重置
    path('password-reset/', include('password_reset.urls')),
    # 通知
    path('inbox/notifications/', include('notifications.urls', namespace='notifications')),
    path('notice/', include('notice.urls', namespace='notice')),
]
handler404 = page_not_found

notice/urls.py
from django.urls import path
from . import views

app_name = 'notice'

urlpatterns = [
    # 通知列表
    path('list/', views.CommentNoticeListView.as_view(), name='list'),
    # 更新通知状态
    path('update/', views.CommentNoticeUpdateView.as_view(), name='update'),
]

notice/models.py
from django.db import models

# Create your models here.

notice/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render,redirect

# Create your views here.
from django.views import View
from django.views.generic import ListView

# LoginRequiredMixin混入类验证是否登录
from article.models import ArticlePost


class CommentNoticeListView(LoginRequiredMixin,ListView):
    """通知列表"""

    context_object_name = 'notices'
    template_name = 'notice/list.html'
    # 登录重定向路由
    login_url = 'userprofile/login/'

    def get_queryset(self):
        """处理查询集"""
        return self.request.user.notifications.unread()


class CommentNoticeUpdateView(View):
    """更新通知状态"""
    def get(self, request):
        # 获取未读消息
        notice_id = request.GET.get('notice_id')
        if notice_id:
            article = ArticlePost.objects.get(id=request.GET.get('article_id'))
            # notifications内置函数，标记一条notice为已读
            request.user.notifications.get(id=notice_id).mark_as_read()
            return redirect(article)    # redirect model对象时,model中需要有get_absolute_url方法
        # 点击清空全部按钮
        else:
            request.user.notifications.mark_all_as_read()
            return redirect('notice:list')

templates/notice/list.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    通知
{% endblock title %}

{% block content %}
    <div class="container">
        <div class="row mt-4 ml-4">
            {% load notifications_tags %}
            {% notifications_unread as unread_count %}
            {% if unread_count %}
            <a href="{% url "notice:update" %}" class="btn btn-secondary" role="button">清空所有通知</a>
            {% else %}
            <h4>暂时还没有通知。</h4>
            {% endif %}

        </div>
        <!-- 未读通知列表 -->
        <div class="row mt-2 ml-4">
            <ul class="list-group">
                {% for notice in notices %}
                    <li class="list-group-item" id="notice_link">
                        <a href="{% url "notice:update" %}?article_id={{ notice.target.id }}&notice_id={{ notice.id }}#comment_elem_{{ notice.action_object.id }}"
                           target="_blank"
                        >
                    <span style="color: #5897fb;">
                        {{ notice.actor }}
                    </span>
                            在 <span style="color: #01a252;">{{ notice.target }}</span> {{ notice.verb }}。
                        </a>
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ notice.timestamp|date:"Y/m/d H:i" }}
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>

    <style>
        #notice_link a:link {
            color: black;
        }

        #notice_link a:visited {
            color: lightgrey;
        }
    </style>
{% endblock content %}