article/urls.py
from django.urls import path

# 正在部署的应用的名称
from article import views

app_name = 'article'

urlpatterns = [
    path('article-list/', views.article_list, name='article_list'),
    path('article-detail/<int:id>/', views.article_detail, name='article_detail'),
    path('article-create/', views.article_create, name='article_create'),
    path('article-delete/<int:id>/', views.article_delete, name='article_delete'),
    path('article-update/<int:id>/', views.article_update, name='article_update'),

    # 点赞 +1
    path('increase-likes/<int:id>/', views.IncreaseLikesView.as_view(),name='increase_likes'),
]

my_blog/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

from article.views import article_list, page_not_found

urlpatterns = [
    path('', article_list, name='home'),
    # 启用media
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}, name='media'),

    path('admin/', admin.site.urls),
    # 文章
    path('article/', include('article.urls', namespace='article')),

    # 评论
    path('comment/', include('comment.urls', namespace='comment')),

    # 用户
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),

    # 引用轮子
    # 密码重置
    path('password-reset/', include('password_reset.urls')),
    # 通知
    path('inbox/notifications/', include('notifications.urls', namespace='notifications')),
    path('notice/', include('notice.urls', namespace='notice')),
]
handler404 = page_not_found

notice/urls.py
from django.urls import path
from . import views

app_name = 'notice'

urlpatterns = [
    # 通知列表
    path('list/', views.CommentNoticeListView.as_view(), name='list'),
    # 更新通知状态
    path('update/', views.CommentNoticeUpdateView.as_view(), name='update'),
]

userprofile/urls.py
from django.urls import path

# 正在部署的应用的名称
from userprofile import views

app_name = 'userprofile'

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.user_register, name='register'),
    path('delete/<int:id>/', views.user_delete, name='delete'),
    path('edit/<int:id>/', views.profile_edit, name='edit'),
]

templates/back_to_top_func.html
<button type="button" id="BackTop" class="toTop-arrow" style="z-index: 100;"></button>

<script>
    // 向上滚动的函数
    $(function () {
        $('#BackTop').click(function () {
            $('html,body').animate({scrollTop: 0}, 500);
        });
        $(window).scroll(function () {
            if ($(this).scrollTop() > 300) {
                $('#BackTop').fadeIn(300);
            } else {
                $('#BackTop').stop().fadeOut(300);
            }
        }).scroll();
    });
</script>

<style>
    /* 按钮边框的大小、位置、样式 */
    .toTop-arrow {
        width: 3.5rem;
        height: 3.5rem;
        padding: 0;
        margin: 0;
        border: 0;
        border-radius: 33%;
        opacity: 0.7;
        background: #c4c2c2;
        cursor: pointer;
        position: fixed;
        right: 1.5rem;
        bottom: 1.5rem;
        display: none;
    }

    /* 绘制按钮中的向上箭头 */
    .toTop-arrow::before, .toTop-arrow::after {
        width: 31px;
        height: 7px;
        border-radius: 3px;
        background: #ffffff;
        position: absolute;
        content: "";
    }

    .toTop-arrow::before {
        transform: rotate(-45deg) translate(0, -50%);
        left: 0.4rem;
    }

    .toTop-arrow::after {
        transform: rotate(45deg) translate(0, -50%);
        right: 0.4rem;
    }

    /* 取消点击按钮时的聚焦 */
    .toTop-arrow:focus {
        outline: none;
    }
</style>

templates/base.html
{% load static %}


<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">

    <link rel="stylesheet" href="{% static 'font-awesome/css/font-awesome.min.css' %}">

    <style>
        html, body {
            height: 100%;
            margin: 0;
        }

        #wrapper {
            min-height: 100%;
            margin-bottom: -60px;
        }

        #footer, #push {
            height: 60px;
        }
    </style>
{% block css %}{% endblock %}

</head>
<body>

<!-- 引入导航栏 -->
{% include 'header.html' %}
<!-- 预留具体页面的位置 -->
<div id="wrapper">
    {% block content %}{% endblock content %}
    <div id="push"></div>
</div>
<!-- 引入注脚 -->
{% include 'footer.html' %}

<script src="{% static 'jquery/jquery-3.6.0.min.js' %}"></script>
{#<script src="https://cdn.bootcdn.net/ajax/libs/popper.js/1.5.1/popper.es5.js "></script>#}
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'layer/layer.js' %}"></script>

{% include 'back_to_top_func.html' %}

{% block js %}{% endblock %}


</body>
</html>

templates/footer.html
{% load static %}
<!-- Footer -->

<footer id="footer" class="py-2 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; 2022 beyond24</p>
        <p class="m-0 text-center text-white">豫ICP备2022005269 | 网站运行在阿里云</p>
    </div>
</footer>

templates/header.html
<!-- 定义导航栏 -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">

        <!-- 导航栏商标 -->
        <a class="navbar-brand" href="{% url 'article:article_list' %}">beyond的个人博客</a>

        <!-- 导航入口 -->
        <div>
            <ul class="navbar-nav">
                <!-- 条目 -->
                <li class="nav-item">
                    {% if user.is_superuser %}
                        <a class="nav-link" href="{% url 'article:article_create' %}">写文章</a>
                    {% endif %}
                </li>
                {% if user.is_authenticated %}
                    <!-- 如果用户已经登录，则显示用户名下拉框 -->
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <!-- 引入notifications的模板标签 -->
                            {% load notifications_tags %}
                            {% notifications_unread as unread_count %}
                            {% if unread_count %}
                                <i style="color: red;font-size: 10px" class="fa fa-circle" aria-hidden="true"></i>
                            {% endif %}

                            {{ user.username }}
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{% url 'notice:list' %}">通知
                                {% if unread_count %}
                                    <span class="badge badge-danger">{{ unread_count }}</span>
                                {% endif %}
                            </a>
                            <a class="dropdown-item" href='{% url "userprofile:edit" user.id %}'>个人信息</a>
                            <a class="dropdown-item" href="#" onclick="user_delete()">删除用户</a>
                            <a class="dropdown-item" href="{% url 'userprofile:logout' %}">退出登录</a>


                        </div>
                    </li>
                    <!-- 如果用户未登录，则显示 “登录” -->
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'userprofile:login' %}">登录</a>
                    </li>
                    <!-- if 语句在这里结束 -->
                {% endif %}
            </ul>
        </div>

    </div>
</nav>

{% if user.is_authenticated %}
    <form
            style="display:none;"
            id="user_delete"
            action="{% url 'userprofile:delete' user.id %}"
            method="POST"
    >
        {% csrf_token %}
        <button type="submit">发送</button>
    </form>
    <script>
        function user_delete() {
            // 调用layer弹窗组件
            layer.open({
                title: "确认删除",
                content: "确认删除用户资料吗？",
                yes: function (index, layero) {
                    $('form#user_delete button').click();
                    layer.close(index);
                },
            })
        }
    </script>
{% endif %}